language: cpp
compiler: clang
os: linux
dist: bionic

stages:
  - compile
  - lint
  - test
  - documentation

before_script:
  - cd Team11/Code11
  - mkdir build
  - cd build

jobs:
  include:
    - stage: compile
      name: "all in one"
      script: 
        - cmake ..
        - make
        - cd src/unit_testing 
        - ./unit_testing
        - cd ../../src/integration_testing
        - ./integration_testing
