language: cpp
compiler: clang
os: linux
dist: bionic

stages:
  - compile
  - lint
  - test

before_script:
  - cd Team00/Code00
  - mkdir build
  - cd build

jobs:
  include:
    - stage: compile
      name: "Compilation"
      script: 
        - cmake ..
        - make
