language: cpp
compiler: 
  - clang
os: 
  - linux
dist: bionic

stages:
  - compile
  - lint
  - test
  - documentation

before_script:
  - cd Team00/Code00
  - mkdir build
  - cd build

jobs:
  include:
    - stage: compile
      name: "Compilation"
      script: 
        - cmake ..
        - make
    
    - stage: test
      name: "Unit Testing"
      script:
        - cmake ..
        - make 
        - cd src/unit_testing 
        - ./unit_testing

    - stage: test
      name: "Integration Testing"
      script:
        - cmake ..
        - make
        - cd src/integration_testing
        - ./integration_testing
